{"config":{"scriptInfo":{"script":"import com.flowable.indexing.ElasticsearchClient\n\ndef result = elasticsearchClient.query(\"tasks\", \"{\\\"size\\\": 0, \\\"track_total_hits\\\": true, \\\"query\\\": {\\\"bool\\\": {\\\"must\\\": [{ \\\"term\\\": { \\\"parentScopeDefinitionKey\\\": \\\"tooManyVariables\\\" } }]}},   \\\"aggs\\\": {\\\"by_user\\\": {\\\"terms\\\": {\\\"field\\\": \\\"assignee\\\", \\\"size\\\": 100, \\\"min_doc_count\\\": 1, \\\"order\\\": { \\\"_count\\\": \\\"desc\\\" }, \\\"missing\\\": \\\"_MISSING_\\\"}}}}\", true)\n\nflw.setOutput(\"result\", result)","language":"groovy"}},"ignoreConfirmationMessage":true,"botKey":"platform-script-evaluation-bot","name":"Get Aggs Query","key":"getAggsQuery"}